version: 3

tasks:
  clean:
    cmds:
      - rm courses.json quizzes.json cache.json 2> /dev/null &
      - rm -rf school dump 2> /dev/null &
      - mkdir school dump
    silent: true

  run:backend:
    cmds:
      - go run ./cmd/curaitor/main.go

  run:frontend:
    cmds:
      - cd ui && pnpm dev
